name: KuduBul
favicon: null
layout_spectrum: 0.0028
typography_spectrum: 0.9306143163703382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.810719279339537
  lightness: 0.07227490842342377
  saturation: 0.7599538022186607
  rhythmicContrast: 0.32537521072663367
purpose: []
