name: KuduBul
favicon: null
layout_spectrum: 0.21111
typography_spectrum: 0.4851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#108c94'
    - '#222f35'
    - '#f8f5f0'
    - '#5a5a62'
    - '#98baac'
  brandStrength: 0.8125
  lightness: 0.07227490842342377
  saturation: 0.7599538022186607
  rhythmicContrast: 0.32537521072663367
purpose: []
